version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pagasa_db
    restart: always
    environment:
      POSTGRES_USER: pcappuser
      POSTGRES_PASSWORD: PagasaWarrior23
      POSTGRES_DB: pagasa-centre-db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/migrations  # mount for goose migrations
    networks:
      - pagasa-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pagasa_api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - pagasa-network

  goose:
    image: kukymbr/goose-docker:3.24.1
    container_name: goose_migrator
    depends_on:
      - db
    entrypoint: >
      /bin/sh -c "
        sleep 5 &&
        goose -dir=/migrations postgres 'postgres://pcappuser:PagasaWarrior23@db:5432/pagasa-centre-db?sslmode=disable' up
      "
    volumes:
      - ./migrations:/migrations
    networks:
      - pagasa-network

volumes:
  pgdata:

networks:
  pagasa-network: