output   = "internal/entity"
pkgname	 = "entity"

# Reference DB config
[psql]
dbname = "pagasa-centre-db"
host = "localhost"
port = 5432
user = "pcappuser"
pass = "PagasaWarrior23"
sslmode = "disable"
blacklist = ["migrations"] # optional: tables to exclude
use-foreign-keys = true