package domain

const (
	RolePrimary                        = "Primary"
	RolePastor                         = "Pastor"
	RoleMediaMinistryLeader            = "Media Ministry Leader"
	RoleMediaMinistryMember            = "Media Ministry Member"
	RoleProductionMinistryLeader       = "Production Ministry Leader"
	RoleProductionMinistryMember       = "Production Ministry Member"
	RoleChildrensMinistryLeader        = "Children's Ministry Leader"
	RoleChildrensMinistryMember        = "Children's Ministry Member"
	RoleMusicMinistryLeader            = "Music Ministry Leader"
	RoleMusicMinistryMember            = "Music Ministry Member"
	RoleCreativeArtsMinistryLeader     = "Creative Arts Ministry Leader"
	RoleCreativeArtsMinistryMember     = "Creative Arts Ministry Member"
	RoleUsheringSecurityMinistryLeader = "Ushering & Security Ministry Leader"
	RoleUsheringSecurityMinistryMember = "Ushering & Security Ministry Member"
	RoleDisciple                       = "Disciple"
	RoleLeader                         = "Leader"
	RoleChurchMember                   = "Church Member"
	RoleEditor                         = "Editor"
	RolePhotographer                   = "Photographer"
	RoleSundaySchoolTeacher            = "Sunday School Teacher"
	RoleAdmin                          = "Admin"
	RoleMonitor                        = "Monitor"
	RoleLivestreamer                   = "Livestreamer"
	RoleITMinistry                     = "IT Ministry"
)
