// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	CellGroupMembers string
	CellGroups       string
	GooseDBVersion   string
	Ministries       string
	Outreaches       string
	Roles            string
	UserRoles        string
	Users            string
}{
	CellGroupMembers: "cell_group_members",
	CellGroups:       "cell_groups",
	GooseDBVersion:   "goose_db_version",
	Ministries:       "ministries",
	Outreaches:       "outreaches",
	Roles:            "roles",
	UserRoles:        "user_roles",
	Users:            "users",
}
