// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("CellGroups", testCellGroupsUpsert)

	t.Run("GooseDBVersions", testGooseDBVersionsUpsert)

	t.Run("Ministries", testMinistriesUpsert)

	t.Run("Outreaches", testOutreachesUpsert)

	t.Run("Roles", testRolesUpsert)

	t.Run("UserRoles", testUserRolesUpsert)

	t.Run("Users", testUsersUpsert)
}
