// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Approvals", testApprovalsUpsert)

	t.Run("CellGroups", testCellGroupsUpsert)

	t.Run("EventDays", testEventDaysUpsert)

	t.Run("Events", testEventsUpsert)

	t.Run("GooseDBVersions", testGooseDBVersionsUpsert)

	t.Run("Media", testMediaUpsert)

	t.Run("Ministries", testMinistriesUpsert)

	t.Run("OutreachServices", testOutreachServicesUpsert)

	t.Run("Outreaches", testOutreachesUpsert)

	t.Run("Roles", testRolesUpsert)

	t.Run("UserRoles", testUserRolesUpsert)

	t.Run("Users", testUsersUpsert)
}
